# docker-compose.yml
services:
  postgres:
    image: postgres:16
    container_name: dev-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kisal123
      POSTGRES_DB: Test
    ports:
      - "5432:5432"        # expose inside the codespace as localhost:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Test"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
