--
-- PostgreSQL database dump
--

\restrict CiqTHxVVDt8G2vy6U1GCBSGMIzldrNSPz3qq1jRZr665VJJAbKBKIDIXCpeK64H

-- Dumped from database version 16.10 (Debian 16.10-1.pgdg13+1)
-- Dumped by pg_dump version 16.10 (Debian 16.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: baseline_image; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.baseline_image (
    id bigint NOT NULL,
    cloudy_image_url character varying(255),
    rainy_image_url character varying(255),
    sunny_image_url character varying(255),
    transformer_no character varying(255),
    uploaded_by character varying(255),
    uploaded_date character varying(255),
    uploaded_time character varying(255)
);


ALTER TABLE public.baseline_image OWNER TO postgres;

--
-- Name: baseline_image_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.baseline_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.baseline_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inspection; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inspection (
    id bigint NOT NULL,
    inspection_branch character varying(255),
    inspection_date character varying(255),
    inspection_no character varying(255),
    inspection_status character varying(255),
    inspection_time character varying(255),
    thermal_image_condition character varying(255),
    thermal_image_url character varying(255),
    transformer_no character varying(255),
    inspectedby character varying(255)
);


ALTER TABLE public.inspection OWNER TO postgres;

--
-- Name: inspection_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inspection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inspection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inspection_image; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inspection_image (
    id bigint NOT NULL,
    inspection_no character varying(255),
    thermal_image_condition character varying(255),
    thermal_image_url character varying(255),
    transformer_no character varying(255),
    uploaded_by character varying(255),
    uploaded_date character varying(255),
    uploaded_time character varying(255)
);


ALTER TABLE public.inspection_image OWNER TO postgres;

--
-- Name: inspection_image_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inspection_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inspection_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transformer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transformer (
    id bigint NOT NULL,
    base_image_cloudy_url character varying(255),
    base_image_rainy_url character varying(255),
    base_image_sunny_url character varying(255),
    transformer_location character varying(255),
    transformer_no character varying(255),
    transformer_pole_no character varying(255),
    transformer_region character varying(255),
    transformer_type character varying(255),
    transformer_capacity character varying(255)
);


ALTER TABLE public.transformer OWNER TO postgres;

--
-- Name: transformer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transformer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transformer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: baseline_image; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.baseline_image (id, cloudy_image_url, rainy_image_url, sunny_image_url, transformer_no, uploaded_by, uploaded_date, uploaded_time) FROM stdin;
6	https://drive.google.com/file/d/1-Z2zLvScvB9PacytNLY3gvCnZAMkMIBh/view?usp=drivesdk	https://drive.google.com/file/d/12iNyI0yTVMvcMEsyR0A_hNa8LqSJaWRd/view?usp=drivesdk	https://drive.google.com/file/d/1IZytQhibcM2D97xbGyBOUOkhdwrc6ttN/view?usp=drivesdk	AZ-386	Devix	2025-08-27	21:04
7	https://drive.google.com/file/d/1oDPGLQkKxUX4_tCLcit2WTrJs3lVGCut/view?usp=drivesdk	https://drive.google.com/file/d/1wqkwvB4pNPAmAjes0z4HrZGNsEFQKmQZ/view?usp=drivesdk	https://drive.google.com/file/d/1SBpOuHxoQTzuBp9iAKHWcrQTVYGDp8-V/view?usp=drivesdk	AX-457	Devix	2025-08-27	21:06
11	https://drive.google.com/file/d/1XMo7fsG4FNKHq9Aj-967HzN2GH_WzHqV/view?usp=drivesdk	https://drive.google.com/file/d/1ENljo4k8rxZ23YmwaRf_A_SPdqaGFUWU/view?usp=drivesdk	https://drive.google.com/file/d/1_l9amhmxORZyYuYT4wVmHo7r8CIXzcSo/view?usp=drivesdk	AZ-569	Devix	2025-08-27	22:33
12	https://drive.google.com/file/d/1wAOEmykkCkWn8khwMp_9lhbXDqv9pucE/view?usp=drivesdk	https://drive.google.com/file/d/1S_GPSEHNCo2w4YEfW--d5ROEpqDlL5C9/view?usp=drivesdk	https://drive.google.com/file/d/11AbkJ7BZHzSBXx0OJgXudJ5xkRY2uNBJ/view?usp=drivesdk	AZ-679	Devix	2025-08-27	22:35
13	https://drive.google.com/file/d/1h6ZKEs9TlHJUDF7Mb261ZCVzfQFFkbam/view?usp=drivesdk	https://drive.google.com/file/d/1f0bN6suozQkHHHUWG8hbqvgXLJ_x2WlT/view?usp=drivesdk	https://drive.google.com/file/d/1B7vMIbPkTn1VXSGwAutQ9ZHqeouzTWuG/view?usp=drivesdk	AZ-160	Devix	2025-08-27	22:39
\.


--
-- Data for Name: inspection; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inspection (id, inspection_branch, inspection_date, inspection_no, inspection_status, inspection_time, thermal_image_condition, thermal_image_url, transformer_no, inspectedby) FROM stdin;
4	South	2025-08-14	00001	\N	09:04	\N	\N	AZ-386	Devix
5	North	2025-08-15	00002	\N	13:06	\N	\N	AX-457	Devix
6	West	2025-08-11	00003	\N	21:10	\N	\N	AX-457	Devix
7	East	2025-08-05	00004	\N	12:09	\N	\N	AX-457	Devix
8	North	2025-08-13	00005	\N	12:10	\N	\N	AZ-386	Devix
9	East	2025-08-06	00006	\N	21:14	\N	\N	AZ-386	Devix
13	North	2025-08-29	00008	\N	10:35	\N	\N	AZ-569	Devix
14	South	2025-09-04	00009	\N	14:34	\N	\N	AZ-569	Devix
15	West	2025-08-28	00010	\N	13:35	\N	\N	AZ-569	Devix
16	North	2025-08-20	00011	\N	22:40	\N	\N	AZ-679	Devix
17	South	2025-08-21	00012	\N	22:41	\N	\N	AZ-679	Devix
18	West	2025-08-21	00013	\N	22:41	\N	\N	AZ-679	Devix
19	North	2025-08-28	00014	\N	13:40	\N	\N	AZ-160	Devix
20	South	2025-08-12	00015	\N	01:40	\N	\N	AZ-160	Devix
21	West	2025-08-13	00016	\N	22:43	\N	\N	AZ-160	Devix
\.


--
-- Data for Name: inspection_image; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inspection_image (id, inspection_no, thermal_image_condition, thermal_image_url, transformer_no, uploaded_by, uploaded_date, uploaded_time) FROM stdin;
4	00001	Rainy	https://drive.google.com/file/d/1mWDlTgDRi5B-7pz0Qcn2J4OhvvQM3oy8/view?usp=drivesdk	AZ-386	Devix	2025-08-27	21:05
5	00002	Cloudy	https://drive.google.com/file/d/17sd5LLxcMqPMlg1bWsRm-7vzKRxG40xV/view?usp=drivesdk	AX-457	Devix	2025-08-27	21:07
6	00003	Sunny	https://drive.google.com/file/d/1ReO6pTD7zu80qVQs3LlWtA-6AIZBWoaa/view?usp=drivesdk	AX-457	Devix	2025-08-27	21:08
7	00004	Rainy	https://drive.google.com/file/d/14N0Wt8rfaKI2i6HT59P9yJ1CGe1wHlc0/view?usp=drivesdk	AX-457	Devix	2025-08-27	21:09
8	00005	Cloudy	https://drive.google.com/file/d/1PjMbImSZFlUoCaRY_pN6JE7DTEdzUUiX/view?usp=drivesdk	AZ-386	Devix	2025-08-27	21:10
9	00006	Rainy	https://drive.google.com/file/d/1zH4OUUfMiNsJC_UO594pQ2ioIF3veGdh/view?usp=drivesdk	AZ-386	Devix	2025-08-27	21:11
13	00008	Sunny	https://drive.google.com/file/d/1qJUPK3CuszPzScGZCJ9qn-ruZkW4Ff2w/view?usp=drivesdk	AZ-569	Devix	2025-08-27	22:33
14	00009	Cloudy	https://drive.google.com/file/d/1HKoaAq9PdSj-UkBspdYg9OjJHBeZhAqi/view?usp=drivesdk	AZ-569	Devix	2025-08-27	22:34
15	00010	Rainy	https://drive.google.com/file/d/1_w2YEWhF9YpfjjxowS4yaI_JsuZr0D1j/view?usp=drivesdk	AZ-569	Devix	2025-08-27	22:35
16	00011	Sunny	https://drive.google.com/file/d/1hG4yepBRfJN2YLE5s-PuWS5CAvYkOCTY/view?usp=drivesdk	AZ-679	Devix	2025-08-27	22:36
17	00012	Cloudy	https://drive.google.com/file/d/1TbxTU7_7qPgkqUCjv6KaaKWei3cjmlxi/view?usp=drivesdk	AZ-679	Devix	2025-08-27	22:36
18	00013	Rainy	https://drive.google.com/file/d/1cV8BsMqX78oSnCsvej_n9SnBLXEOZ9Zv/view?usp=drivesdk	AZ-679	Devix	2025-08-27	22:37
19	00014	Sunny	https://drive.google.com/file/d/1kc8wwHj5uff7SUBDnmAyF84diD8GT-4v/view?usp=drivesdk	AZ-160	Devix	2025-08-27	22:40
20	00015	Cloudy	https://drive.google.com/file/d/1RTEbWQhzpnWIfheVm-j0BEdPD_j6ZWWb/view?usp=drivesdk	AZ-160	Devix	2025-08-27	22:40
21	00016	Rainy	https://drive.google.com/file/d/1tvgQJv0a0hzTyAFewMBbOXS3KsfRbpsU/view?usp=drivesdk	AZ-160	Devix	2025-08-27	22:41
\.


--
-- Data for Name: transformer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transformer (id, base_image_cloudy_url, base_image_rainy_url, base_image_sunny_url, transformer_location, transformer_no, transformer_pole_no, transformer_region, transformer_type, transformer_capacity) FROM stdin;
8	\N	\N	\N	Colombo 7	AZ-386	198	Colombo	Bulk	120
4	\N	\N	\N	Dehiwala	AX-457	145	Dehiwala-Mount Lavinia	Bulk	1200
5	\N	\N	\N	Panadura 2	AZ-569	150	Panadura	Distribution	103
6	\N	\N	\N	Katubedda	AZ-679	160	Moratuwa	Distribution	120
19	\N	\N	\N	Colombo 2	AZ-160	456	Colombo	Bulk	102
\.


--
-- Name: baseline_image_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.baseline_image_id_seq', 13, true);


--
-- Name: inspection_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inspection_id_seq', 21, true);


--
-- Name: inspection_image_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inspection_image_id_seq', 21, true);


--
-- Name: transformer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transformer_id_seq', 19, true);


--
-- Name: baseline_image baseline_image_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.baseline_image
    ADD CONSTRAINT baseline_image_pkey PRIMARY KEY (id);


--
-- Name: inspection_image inspection_image_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inspection_image
    ADD CONSTRAINT inspection_image_pkey PRIMARY KEY (id);


--
-- Name: inspection inspection_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inspection
    ADD CONSTRAINT inspection_pkey PRIMARY KEY (id);


--
-- Name: transformer transformer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transformer
    ADD CONSTRAINT transformer_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict CiqTHxVVDt8G2vy6U1GCBSGMIzldrNSPz3qq1jRZr665VJJAbKBKIDIXCpeK64H

