exclude = [
    ".github",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv"
]

# When true, Ruff will apply fixable diagnostics automatically when run
# Note: this mirrors the CLI flag `ruff --fix`. Keeping this in the config
# makes `ruff` behave as if `--fix` was passed when run by tools that read
# this file. Some editors/IDEs also respect this setting.
fix = true

# same as black
line-length = 79
indent-width = 4

[lint]
select = ["E4", "E7", "E9", "F"]
ignore = ["F401", "E731", "E711", "F841", "E741", "F821"]   # Don't remove F401 rule.

fixable = ["E702"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "double"

indent-style = "space"

skip-magic-trailing-comma = false

line-ending = "auto"

docstring-code-format = false

docstring-code-line-length = "dynamic"